name: Deploy Website

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install dependencies (if needed)
    - name: Set up Node.js (if using Node-based build tools)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install # Adjust if you use different package manager or have no dependencies

    - name: Build Site
      run: npm run build # Adjust based on your build step, if not needed you can skip this step

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Replace with the directory that contains your built site
